### ISSUE TITLE
issues about inference on  scannet val-set

### ISSUE THREAD

**Issue by EagleMan11** [neu-vi/PlanarRecon#23]
Hi，my bro
2024-10-31 15:13:02.613 | INFO     | __main__:test:260 - scene0207_01_1
2024-10-31 15:13:02.614 | INFO     | __main__:test:260 - scene0207_02_0
2024-10-31 15:13:02.878 | INFO     | __main__:test:263 - Epoch 68, Iter 43/223, test loss = 0.000, time = 0.264274
2024-10-31 15:13:03.434 | INFO     | __main__:test:260 - scene0207_02_1
2024-10-31 15:13:03.435 | INFO     | __main__:test:260 - scene0208_00_0
2024-10-31 15:13:03.663 | INFO     | __main__:test:263 - Epoch 68, Iter 44/223, test loss = 0.000, time = 0.228511
2024-10-31 15:13:03.978 | INFO     | __main__:test:260 - scene0208_00_1
2024-10-31 15:13:03.978 | INFO     | __main__:test:260 - scene0217_00_0
2024-10-31 15:13:04.234 | INFO     | __main__:test:263 - Epoch 68, Iter 45/223, test loss = 0.000, time = 0.255499
2024-10-31 15:13:05.668 | INFO     | __main__:test:260 - scene0221_00_0
2024-10-31 15:13:05.668 | INFO     | __main__:test:260 - scene0222_00_0
2024-10-31 15:13:05.877 | WARNING  | models.planarrecon_network:forward:267 - no valid points: scale 2, batch 0
2024-10-31 15:13:05.879 | INFO     | __main__:test:263 - Epoch 68, Iter 46/223, test loss = 0.000, time = 0.210160
Traceback (most recent call last):
  File "main.py", line 312, in <module>
    test()
  File "main.py", line 276, in test
    save_mesh_scene(outputs, sample, epoch_idx)
  File "/root/autodl-tmp/PlanarRecon/utils.py", line 434, in __call__
    self.save_scene_eval(epoch_idx, outputs, inputs, i)
  File "/root/autodl-tmp/PlanarRecon/utils.py", line 414, in save_scene_eval
    planes =  np.stack(planes_final)
  File "<__array_function__ internals>", line 180, in stack
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/core/shape_base.py", line 422, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

Is it a problem with my dataset processing? I am using the scannet_frames_25k dataset, which is segmented into 100 frames.

Can I add you on WeChat or something?Thanks

**Comment by Chinafsh** [comment]
> Hi，my bro 2024-10-31 15:13:02.613 | INFO | **main**:test:260 - scene0207_01_1 2024-10-31 15:13:02.614 | INFO | **main**:test:260 - scene0207_02_0 2024-10-31 15:13:02.878 | INFO | **main**:test:263 - Epoch 68, Iter 43/223, test loss = 0.000, time = 0.264274 2024-10-31 15:13:03.434 | INFO | **main**:test:260 - scene0207_02_1 2024-10-31 15:13:03.435 | INFO | **main**:test:260 - scene0208_00_0 2024-10-31 15:13:03.663 | INFO | **main**:test:263 - Epoch 68, Iter 44/223, test loss = 0.000, time = 0.228511 2024-10-31 15:13:03.978 | INFO | **main**:test:260 - scene0208_00_1 2024-10-31 15:13:03.978 | INFO | **main**:test:260 - scene0217_00_0 2024-10-31 15:13:04.234 | INFO | **main**:test:263 - Epoch 68, Iter 45/223, test loss = 0.000, time = 0.255499 2024-10-31 15:13:05.668 | INFO | **main**:test:260 - scene0221_00_0 2024-10-31 15:13:05.668 | INFO | **main**:test:260 - scene0222_00_0 2024-10-31 15:13:05.877 | WARNING | models.planarrecon_network:forward:267 - no valid points: scale 2, batch 0 2024-10-31 15:13:05.879 | INFO | **main**:test:263 - Epoch 68, Iter 46/223, test loss = 0.000, time = 0.210160 Traceback (most recent call last): File "main.py", line 312, in test() File "main.py", line 276, in test save_mesh_scene(outputs, sample, epoch_idx) File "/root/autodl-tmp/PlanarRecon/utils.py", line 434, in **call** self.save_scene_eval(epoch_idx, outputs, inputs, i) File "/root/autodl-tmp/PlanarRecon/utils.py", line 414, in save_scene_eval planes = np.stack(planes_final) File "<**array_function** internals>", line 180, in stack File "/root/miniconda3/lib/python3.8/site-packages/numpy/core/shape_base.py", line 422, in stack raise ValueError('need at least one array to stack') ValueError: need at least one array to stack
> 
> Is it a problem with my dataset processing? I am using the scannet_frames_25k dataset, which is segmented into 100 frames.
> 
> Can I add you on WeChat or something?Thanks

哥，你系统用的什么啊？环境配置是按照他提供的来的吗?
