### ISSUE TITLE
Stuck During Generating Ground Truth

### ISSUE THREAD

**Issue by nbansal90** [neu-vi/PlanarRecon#9]
Hey @ymingxie ,

I am looking to generate groundtruth for ScanNet dataset using the ```tools/generate_gt.py```. 

 I am running the following command as provided by you ```python tools/generate_gt.py --save_name planes_9/ --window_size 9 --n_proc 2 --n_gpu 1```. 
But I find that the script is stuck in the ```load``` stage in file : ```tools/ChamferDistancePytorch/chamfer3D/dist_chamfer_3D.py```

`from torch.utils.cpp_extension import load
  chamfer_3D = load(name="chamfer_3D",
          sources=[
              "/".join(os.path.abspath(__file__).split('/')[:-1] + ["chamfer_cuda.cpp"]),
              "/".join(os.path.abspath(__file__).split('/')[:-1] + ["chamfer3D.cu"]),
              ], build_directory=build_path)`

and is not moving forward.

When I kill the job using `Ctrl + c`.  I see that the following stack.
```^CTraceback (most recent call last):
  File "tools/generate_gt.py", line 33, in <module>
    from tools.ChamferDistancePytorch.chamfer3D import dist_chamfer_3D
  File "./tools/ChamferDistancePytorch/chamfer3D/dist_chamfer_3D.py", line 19, in <module>
    ], build_directory=build_path)
  File "/home/us000146/anaconda3/envs/selfsupervised/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1091, in load
    keep_intermediates=keep_intermediates)
  File "/home/us000146/anaconda3/envs/selfsupervised/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1306, in _jit_compile
    baton.wait()
  File "/home/us000146/anaconda3/envs/selfsupervised/lib/python3.6/site-packages/torch/utils/file_baton.py", line 42, in wait
    time.sleep(self.wait_seconds)
KeyboardInterrupt
```
PS: I find that ```chamfer_cuda.cpp``` and ```chamfer3D.cu``` are present.
**Could you please suggest what I might be missing here.**

**Comment by nbansal90** [comment]
Issue SOLVED!
